routes/web.php
	Route::get('country-edit/{parameter}','CountryController@edit')->name('master.editcountry');
	Route::post('country_edit','CountryController@update')->name('master.updatecountry');
	Route::get('country-delete/{parameter}','CountryController@delete')->name('master.deletecountry');

	//State Details 
	Route::get('state','StateController@index')->name('master.state');
	Route::get('add-state','StateController@addState')->name('master.addstate');
	Route::post('state_save','StateController@save')->name('master.savestate');
	Route::get('state-edit/{parameter}','StateController@edit')->name('master.editstate');
	Route::post('state_edit','StateController@update')->name('master.updatestate');
	Route::get('state-delete/{id}','StateController@delete')->name('master.deletestate');

	//City Details 
	Route::get('city','CityController@index')->name('master.city');
	Route::get('add-city','CityController@addCity')->name('master.addCity');
	//Route::get('get-state-order-list/{country}','CityController@getStates')->name('master.getStates');
	Route::post('city_save','CityController@save')->name('master.citysave');
	Route::get('city-edit/{parameter}','CityController@edit')->name('master.editcity');
	Route::post('city_update','CityController@update')->name('master.updatecity');
	Route::get('city-delete/{id}','CityController@delete')->name('master.deletecity');

	//Company
	Route::get('/company','CompanyController@index')->name('master.company');
	Route::get('/add-company','CompanyController@addCompany')->name('master.addcompany');
	Route::post('/company_save','CompanyController@save')->name('master.companysave');
	Route::get('company-edit/{parameter}','CompanyController@edit')->name('master.companyedit');
	Route::post('company_edit','CompanyController@update')->name('master.companyupdate');
	Route::get('company-delete/{id}','CompanyController@delete')->name('master.deletecompany');

	//Union Branch
	Route::get('unionbranch','UnionBranchController@index')->name('master.unionbranch');
	Route::get('add-unionbranch','UnionBranchController@addUnionBranch')->name('master.addunionbranch');
	Route::post('unionbranch_save','UnionBranchController@save')->name('master.saveunionbranch');
	Route::get('unionbranch-edit/{parameter}','UnionBranchController@edit')->name('master.editunionbranch');
	Route::post('unionbranch_update','UnionBranchController@update')->name('master.updateunionbranch');
	Route::get('unionbranch-delete/{id}','UnionBranchController@delete')->name('master.deleteunionbranch');
	
	//Person Details
	Route::get('persontitle','PersontitleController@index')->name('master.persontitle');
	Route::get('add-title','PersontitleController@addTitle')->name('master.addpersontitle');
	Route::post('persontitle_save','PersontitleController@save')->name('master.savepersontitle');
	Route::get('persontitle-edit/{parameter}','PersontitleController@edit')->name('master.editpersontitle');
	Route::post('persontitle_update','PersontitleController@update')->name('master.updatepersontitle');
	Route::get('persontitle-delete/{id}','PersontitleController@delete')->name('master.deletepersontitle');

	//Relation Details
	Route::get('relation','RelationController@index')->name('master.relation');
	Route::get('add-relation','RelationController@addRelation')->name('master.addrelation');
	Route::post('relation_save','RelationController@save')->name('master.saverelation');
	Route::get('relation-edit/{parameter}','RelationController@edit')->name('master.editrelation');
	Route::post('relation_update','RelationController@update')->name('master.updaterelation');
	Route::get('relation-delete/{id}','RelationController@delete')->name('master.deleterelation');
	
	//Reason Details
	Route::get('reason','ReasonController@index')->name('master.reason');
	Route::get('add-reason','ReasonController@addReason')->name('master.addreason');
	Route::post('reason_save','ReasonController@save')->name('master.savereason');
	//Route::get('reason-view/{parameter}','ReasonController@view')->name('master.reason');
	Route::get('reason-edit/{parameter}','ReasonController@edit')->name('master.editreason');
	Route::post('reason_update','ReasonController@update')->name('master.updatereason');
	Route::get('reason-delete/{id}','ReasonController@delete')->name('master.deletereason');
	
	//Fee Details
	Route::get('fee','FeeController@index')->name('master.fee');
	Route::get('add-fee','FeeController@addFee')->name('master.addfee');
	Route::post('fee_save','FeeController@save')->name('master.savefee');
	//Route::get('fee-view/{parameter}','FeeController@view')->name('master.fee');
	Route::get('fee-edit/{parameter}','FeeController@edit')->name('master.editfee');
	Route::post('fee_update','FeeController@update')->name('master.updatefee');
	Route::get('fee-delete/{id}','FeeController@delete')->name('master.deletefee');
	
	//Race Details
	Route::get('race','RaceController@index')->name('master.race');
	Route::get('add-race','RaceController@addRace')->name('master.addrace');
	Route::post('race_save','RaceController@save')->name('master.saverace');
	//Route::get('race-view/{parameter}','RaceController@view')->name('master.fee');
	Route::get('race-edit/{parameter}','RaceController@edit')->name('master.editrace');
	Route::post('race_update','RaceController@update')->name('master.updaterace');
	Route::get('race-delete/{id}','RaceController@delete')->name('master.deleterace');
	
	//Designation Details
	Route::get('designation','DesignationController@index')->name('master.designation');
	Route::get('add-designation','DesignationController@addDesignation')->name('master.adddesignation');
	Route::post('designation_save','DesignationController@save')->name('master.savedesignation');
	Route::get('designation-edit/{parameter}','DesignationController@edit')->name('master.editdesignation');
	Route::post('update_designation','DesignationController@update')->name('master.updatedesignation');
	Route::get('designation-delete/{id}','DesignationController@delete')->name('master.deletedesignation');
	
	//Status Details
	Route::get('status','StatusController@index')->name('master.status');
	Route::get('add-status','StatusController@addStatus')->name('master.addstatus');
	Route::post('status_save','StatusController@save')->name('master.savestatus');
	Route::get('status-edit/{parameter}','StatusController@edit')->name('master.editstatus');
	Route::post('status_update','StatusController@update')->name('master.updatestatus');
	Route::get('status-delete/{id}','StatusController@delete')->name('master.deletestatus');
	
	//Branch Details
	Route::get('branch','CompanyBranchController@index')->name('master.branch');
	/* 
	Route::get('get-state-list','BranchController@getStateList');
	Route::get('get-cities-list','BranchController@getCitiesList');
	 */
	Route::get('add-branch','CompanyBranchController@addBranch')->name('master.addbranch');
	Route::post('branch_save','CompanyBranchController@save')->name('master.savebranch');
	Route::get('branch-edit/{parameter}','CompanyBranchController@edit')->name('master.editbranch');
	Route::post('branch_update','CompanyBranchController@update')->name('master.updatebranch');
	Route::get('branch-delete/{id}','CompanyBranchController@delete')->name('master.deletebranch');

	//App Form
	Route::resource('appform', 'AppFormController');
	//Roles Form
	Route::resource('roles','RolesController');
	//users Form
	Route::resource('users','UsersController');
	
	Route::get('/changePassword','HomeController@showChangePasswordForm')->name('changepassword');
	Route::post('/changePassword','HomeController@ChangePassword')->name('changePassword');
	//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');

});
/* Master */



//common routes
Route::get('get-state-list','CommonController@getStateList');
Route::get('get-cities-list','CommonController@getCitiesList');
Route::get('get-branch-list','CommonController@getBranchList');
Route::get('get-age','CommonController@getAge');
Route::get('get-fee-options','CommonController@getFeesList');

// commom member functions
Route::post('add-nominee','MemberController@addNominee');
Route::get('get-oldmember-list','MemberController@getoldMemberList');
Route::post('membership_save','MemberController@Save');
Route::post('membership_update','MemberController@update');

//membership
Route::get('membership','MembershipController@index');
Route::get('membership_register','MembershipController@addMember');
Route::get('membership-view/{parameter}','MembershipController@view');
Route::get('membership-edit/{parameter}','MembershipController@edit');

Route::get('membership-delete/{id}','MembershipController@delete');
Route::get('membership_list','MembershipController@new_members');



//Person Tiltle Setup
Route::get('persontitle','PersontitleController@index');
Route::get('add-title','PersontitleController@addTitle');
Route::post('persontitle_save','PersontitleController@save');
Route::get('persontitle-edit/{parameter}','PersontitleController@edit');
Route::post('persontitle_update','PersontitleController@update');
Route::get('persontitle-delete/{id}','PersontitleController@delete');


//Union Branch
Route::get('unionbranch','UnionBranchController@index');
Route::get('add-unionbranch','UnionBranchController@addUnionBranch');
Route::post('unionbranch_save','UnionBranchController@save');
Route::get('unionbranch-edit/{parameter}','UnionBranchController@edit');
Route::post('unionbranch_update','UnionBranchController@update');
Route::get('unionbranch-delete/{id}','UnionBranchController@delete');


Route::get('get-nominee-data','MembershipController@getNomineeData');
Route::post('update-nominee','MembershipController@updateNominee');
Route::get('delete-nominee-data','MembershipController@deleteNominee');

Route::get('delete-fee-data','MembershipController@deleteFee');
Route::get('edit-membership-profile','MemberController@editMemberProfile')->name('member.membership.profile');




Route::get('/maintenance', function () {

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Permissions\HasPermissionsTrait;
use App\Notifications\ResetPassword;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "users";
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	public function sendPasswordResetNotification($token)
	{
	   $this->notify( new ResetPassword($token));
	}
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Support\Facades\Crypt;
use View;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');  
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::all();
        return view('users.users')->with('data',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.add_users');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',
            'password'=>'required',
            'confirm_password'=>'required',
        ],
        [
            'name.required'=>'Please enter User name',
            'email.required'=>'Please enter Valid Email',
            'password.required'=>'Please enter Password',
            'confirm_password.required'=>'Please enter Confirm Password',
        ]);
       
        $User = new User();
        $User->name = $request->name;
        $User->email = $request->email;
        $User->password = $request->password;
       
        if($User->password == $request->confirm_password)
        {
            $User->password = Crypt::encrypt($User->password);
            $User->save();
            $defdaultLang = app()->getLocale();
            return redirect($defdaultLang.'/users')->with('message','User Details Added Successfully!!');
        }
        else
        {
            $defdaultLang = app()->getLocale();
            return redirect($defdaultLang.'/add_users')->with('error','Paasword and Confirm password mismatch!!');
        }  
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($lang,$id)
    {
        $id = Crypt::decrypt($id);
        
        $User = new User();
        $data['users_edit'] = User::find($id)->first();
       
        return view('users.edit_users')->with('data',$data);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$lang, $id)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',    
        ],
        [
            'name.required'=>'Please enter User name',
            'email.required'=>'Please enter Valid Email',
        ]);
       
        $User = new User();
        $User = User::find($id);
        $User->name = $request->name;
        $User->email = $request->email;
        $User->save();
        $defdaultLang = app()->getLocale();
        return redirect($defdaultLang.'/users')->with('message','User Details Updated Successfully!!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $User = new User();
        $User = User::find($id);
        $User->delete();

        $defdaultLang = app()->getLocale();
        return redirect($defdaultLang.'/roles')->with('message','User Details Deleted Successfully!!');
    }
}

resources/views/users/add_users.blade.php
@extends('layouts.admin')
@section('headSection')
@endsection
@section('headSecondSection')
@endsection
@section('main-content')
<div id="main">
    <div class="row">
        <div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
        <div class="col s12">
            <div class="container">
                <div class="section section-data-tables">
                    <!-- BEGIN: Page Main-->
                    <div class="row">
                        <div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
                            <!-- Search for small screen-->
                            <div class="container">
                                <div class="row">
                                    <div class="col s10 m6 l6">
                                        <h5 class="breadcrumbs-title mt-0 mb-0">{{__('Users List') }}</h5>
                                        <ol class="breadcrumbs mb-0">
                                            <li class="breadcrumb-item"><a href="{{ route('home', app()->getLocale())  }}">{{__('Dashboard') }}</a>
                                            </li>
                                            <li class="breadcrumb-item active"><a href="{{route('users.index',app()->getLocale())}}">{{__('Users') }}</a>
                                            </li>
                                        </ol>
                                    </div>
                                    <div class="col s2 m6 l6 ">
                                        <a class="btn waves-effect waves-light breadcrumbs-btn right" href="{{ route('users.index',app()->getLocale()) }}">{{__('Back') }}</a>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12">
                            <div class="card">
                                <div class="card-content">
                                    <h4 class="card-title ">{{ __('Add Users') }}</h4>
                                    @include('includes.messages')
                                   <div id="view-validations">
                                    <form class="formValidate" id="UsersformValidate" method="post" action="{{ route('users.store',app()->getLocale()) }}">
                                        @csrf
                                      <div class="row">
                                        <div class="input-field col s12 m6">
                                          <label for="name" class="common-label">{{__('Name') }}*</label>
                                          <input id="name" class="common-input" name="name" type="text" data-error=".errorTxt1">
                                          <div class="errorTxt1"></div>
                                        </div>
                                        <div class="input-field col s12 m6">
                                          <label for="email" class="common-label">{{__('email') }}*</label>
                                          <input id="email" class="common-input" name="email" type="email" data-error=".errorTxt2">
                                          <div class="errorTxt2"></div>
                                        </div>
                                        <div class="input-field col s12 m6">
                                          <label for="password" class="common-label">{{__('Password') }}*</label>
                                          <input id="password" class="common-input" name="password" type="password" data-error=".errorTxt2">
                                          <div class="errorTxt2"></div>
                                        </div>
                                        <div class="input-field col s12 m6">
                                          <label for="password" class="common-label">{{__('Confirm Password') }}*</label>
                                          <input id="confirm_password" class="common-input" name="confirm_password" type="password" data-error=".errorTxt2">
                                          <div class="errorTxt2"></div>
                                        </div>
                                        <div class="clearfix" style="clear:both"></div>
                                        <div class="input-field col s12">
                                          <button class="btn waves-effect waves-light right submit" type="submit" name="action">{{__('Save')}}
                                            <!-- <i class="material-icons right">send</i> -->
                                          </button>
                                        </div>
                                      </div>
                                    </form>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END: Page Main-->
                    @include('layouts.right-sidebar')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('footerSection')
<script src="{{ asset('public/assets/vendors/jquery-validation/jquery.validate.min.js')}}"></script>
@endsection
@section('footerSecondSection')
<script src="{{ asset('public/assets/js/scripts/form-validation.js')}}" type="text/javascript"></script>
<script>
	$("#masters_sidebars_id").addClass('active');
	$("#users_sidebar_li_id").addClass('active');
	$("#users_sidebar_a_id").addClass('active');
</script>
<script>
    $("#RolesformValidate").validate({
        rules: {
            name:{
                required: true,
            },
            email:{
                required: true,
            },
            password: {
                required: true,
            }
            confirm_password : {

                required: true,
            },
        },
        //For custom messages
        messages: {
            
            name: {
                required: '{{__("Please enter Name") }}', 
            },
            email:{
                required: '{{__("Please enter Valid Email") }}',
            },
            password: {
                required: '{{__("Please enter Password") }}',
            },
            confirm_password : {
                required: '{{__("Please enter Confirm Password") }}',
            },
        },
        errorElement: 'div',
        errorPlacement: function (error, element) {
        var placement = $(element).data('error');
        if (placement) {
            $(placement).append(error)
        } else {
            error.insertAfter(element);
        }
        }
    });
</script>
@endsection

resources/views/users/edit_users.blade.php
@extends('layouts.admin')
@section('headSection')
@endsection
@section('headSecondSection')
@endsection
@section('main-content')
<div id="main">
    <div class="row">
        <div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
        <div class="col s12">
            <div class="container">
                <div class="section section-data-tables">
                    <!-- BEGIN: Page Main-->
                    <div class="row">
                        <div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
                            <!-- Search for small screen-->
                            <div class="container">
                                <div class="row">
                                    <div class="col s10 m6 l6">
                                        <h5 class="breadcrumbs-title mt-0 mb-0">{{__('Users List') }}</h5>
                                        <ol class="breadcrumbs mb-0">
                                            <li class="breadcrumb-item"><a href="{{ route('home', app()->getLocale())  }}">{{__('Dashboard') }}</a>
                                            </li>
                                            <li class="breadcrumb-item active"><a href="{{route('users.index',app()->getLocale())}}">{{__('Users') }}</a>
                                            </li>
                                        </ol>
                                    </div>
                                    <div class="col s2 m6 l6 ">
                                        <a class="btn waves-effect waves-light breadcrumbs-btn right" href="{{ route('users.index',app()->getLocale()) }}">{{__('Back') }}</a> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12">
                            <div class="card">
                                <div class="card-content">
                                    <h4 class="card-title ">{{ __('Edit Users') }}</h4>
                                    @include('includes.messages')
                                   <div id="view-validations">
                                    <form class="formValidate" id="UsersformValidate" method="post" action="{{ route('users.update',[app()->getLocale(),$data['users_edit']->id]) }}">
                                    <?php $row = $data['users_edit'][0]; ?>
                                        @method('PATCH')
                                        @csrf
                                      <div class="row">
                                      <div class="input-field col s12 m6">
                                          <label for="name" class="common-label">{{__('Name') }}*</label>
                                          <input id="name" class="common-input" value="<?php echo $data['users_edit']->name; ?>" name="name" type="text" data-error=".errorTxt1">
                                          <div class="errorTxt1"></div>
                                        </div>
                                        <div class="input-field col s12 m6">
                                          <label for="email" class="common-label">{{__('email') }}*</label>
                                          <input id="email" class="common-input" value="<?php echo $data['users_edit']->email; ?>" name="email" type="email" data-error=".errorTxt2">
                                          <div class="errorTxt2"></div>
                                        </div>
                                        
                                        <div class="clearfix" style="clear:both"></div>
                                        <div class="input-field col s12">
                                          <button class="btn waves-effect waves-light right submit" type="submit" name="action">{{__('Update')}}
                                            <!-- <i class="material-icons right">send</i> -->
                                          </button>
                                        </div>
                                      </div>
                                    </form>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END: Page Main-->
                    @include('layouts.right-sidebar')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('footerSection')
<script src="{{ asset('public/assets/vendors/jquery-validation/jquery.validate.min.js')}}"></script>
@endsection
@section('footerSecondSection')
<script src="{{ asset('public/assets/js/scripts/form-validation.js')}}" type="text/javascript"></script>
<script>
	$("#masters_sidebars_id").addClass('active');
	$("#users_sidebar_li_id").addClass('active');
	$("#users_sidebar_a_id").addClass('active');
</script>
<script>
    $("#RolesformValidate").validate({
        rules: {
            name:{
                required: true,
            },
            slug:{
                required: true,
            },
        },
        //For custom messages
        messages: {
            
            name: {
                required: '{{__("Please enter Name") }}', 
            },
            slug:{
                required: '{{__("Please enter Slug") }}',
            },
        },
        errorElement: 'div',
        errorPlacement: function (error, element) {
        var placement = $(element).data('error');
        if (placement) {
            $(placement).append(error)
        } else {
            error.insertAfter(element);
        }
        }
    });
</script>
@endsection

resources/views/users/users.blade.php
@extends('layouts.admin')
@section('headSection')
<link rel="stylesheet" type="text/css" href="{{ asset('public/assets/vendors/flag-icon/css/flag-icon.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('public/assets/vendors/data-tables/css/jquery.dataTables.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('public/assets/vendors/data-tables/extensions/responsive/css/responsive.dataTables.min.css') }}">
@endsection
@section('headSecondSection')
<link rel="stylesheet" type="text/css" href="{{ asset('public/assets/css/pages/data-tables.css') }}">
@endsection
@section('main-content')
<div id="main">
	<div class="row">
		<div class="content-wrapper-before gradient-45deg-indigo-purple"></div>
		<div class="col s12">
			<div class="container">
				<div class="section section-data-tables">
					<!-- BEGIN: Page Main-->
					<div class="row">
						<div class="breadcrumbs-dark pb-0 pt-4" id="breadcrumbs-wrapper">
							<!-- Search for small screen-->
							<div class="container">
								<div class="row">
									<div class="col s10 m6 l6">
										<h5 class="breadcrumbs-title mt-0 mb-0">{{__('Users List') }}</h5>
										<ol class="breadcrumbs mb-0">
											<li class="breadcrumb-item"><a href="{{ route('home', app()->getLocale())  }}">{{__('Dashboard') }}</a>
											</li>
											<li class="breadcrumb-item active">{{__('users') }}
											</li>
											
										</ol>
									</div>
									<div class="col s2 m6 l6 ">
										<a class="btn waves-effect waves-light breadcrumbs-btn right" href="{{route('users.create',app()->getLocale())}}">{{__('Add New User') }}</a>
										
									</div>
								</div>
							</div>
						</div>
						<div class="col s12">
							<div class="card">
								<div class="card-content">
									<h4 class="card-title">{{__('Users List') }}</h4>
									@include('includes.messages')
									<div class="row">
										<div class="col s12">
											<table id="page-length-option" class="display">
												<thead>
													<tr>
														<th>{{__('User Name') }}</th>
                                                        <th>{{__('Email') }}</th>
														<th style="margin-left:20px"> {{__('Action') }}</th>
													</tr>
												</thead>
												<tbody>
													@foreach($data as $key=>$value)
													<?php
													 $id = Crypt::encrypt($value->id);  
													 ?>
                                                        <tr>
                                                            <td>{{$value->name}}</td>
                                                            <td>{{$value->email}}</td>
                                                            @php
															{{ $confirmAlert = __("Are you sure you want to delete?"); }}
															@endphp
															<td><a style="float: left;" class="btn-small waves-effect waves-light cyan" href="{{ route('users.edit',[app()->getLocale(),$id]) }}">{{__('Edit') }}</a> <form style="float: left;margin-left:5px;" action="{{ route('users.destroy',[app()->getLocale(),$value->id])}}" method="POST">
															{{ method_field('DELETE') }}
    														{{ csrf_field() }}									
															 <button  type="submit" class="btn-small waves-effect waves-light amber darken-4"  onclick="if (confirm('{{ $confirmAlert }}')) return true; else return false;">{{__('Delete') }}</button> </form></td>
													    </tr>
                                                    @endforeach
												</tbody>
												
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- END: Page Main-->
					@include('layouts.right-sidebar')
				</div>
			</div>
		</div>
	</div>
</div>
@endsection
@section('footerSection')
<script src="{{ asset('public/assets/vendors/data-tables/js/jquery.dataTables.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/vendors/data-tables/js/dataTables.select.min.js') }}" type="text/javascript"></script>
@endsection
@section('footerSecondSection')
<script src="{{ asset('public/assets/js/scripts/data-tables.js') }}" type="text/javascript"></script>
<script>
	$("#masters_sidebars_id").addClass('active');
	$("#users_sidebar_li_id").addClass('active');
	$("#users_sidebar_a_id").addClass('active');
</script>
@endsection